#ifndef STRINGFUNCTIONS_DEFINES
#define STRINGFUNCTIONS_DEFINES
#include <stddef.h>
#include <stdlib.h>
typedef char* mystr;
#define STRINGIND_ERRO -1
#define STRING_END 0

//LASTERRO
typedef enum ENUM_STRINGFUNCTION_LASTERRO{
  STRINGFUNCTION_LASTERRO_NOERRO=0,
  STRINGFUNCTION_LASTERRO_PTRNULL,
  STRINGFUNCTION_LASTERRO_NOCONTENT,
  STRINGFUNCTION_LASTERRO_FILTERNOCONTENT,
  STRINGFUNCTION_LASTERRO_MALLOCERROR,
}STRINGFUNCTION_LASTERRO;

#endif // STRINGFUNCTIONS_DEFINES

